### ISSUE TITLE
Kundensuche

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/sap-hana#2]
Schreibe einen SQL Query:

Gegeben: Kundennummer, PLZ, Name, LIMIT
Rückgabe: Finde alle Kundern, die auf die Eingabe passen, wobei möglichst "fuzzy" gesucht werden sollte

**Comment by frederike-ramin** [comment]
Das wäre so meine (bisher ungetestete, weil zu doof) vorläufige Lösung. (Danke für den Sceleton Code, Christian. ;))

def printResults(resultSet: ResultSet): Unit = {
    while (resultSet.next()) {
      println(resultSet)
    }
  }

  def selectCustomers(kdnr: String = "", plz: String = "", name: String = ""): Unit = {
    try {
      val statement = connection.get.createStatement()
      if kdnr != "" {
        val resultSet = statement.executeQuery("SELECT * FROM SAPQ92.KNA1_HPI WHERE LOWER(KUNDE) LIKE LOWER('" + kdnr + "') LIMIT 100")
        printResults(resultSet)
      } else {
        if (plz != "" || name != "") {
          val resultSet = statement.executeQuery("SELECT * FROM SAPQ92.KNA1_HPI " +
            "WHERE LOWER(NAME) LIKE LOWER('" + name + "')OR PLZ LIKE '" + plz + "' LIMIT 100")
          printResults(resultSet)
        }
        else {
          println("Please insert at least one characteristic of the customer.")
        }
      } catch {
        case e: Throwable => e.printStackTrace()
      }
    }
  }
