### ISSUE TITLE
Offene Posten

### ISSUE THREAD

**Issue by Blaidd-Drwg** [cmfcmf/sap-hana#28]
SQL-Query
Gegeben: Kunde, Enddatum
Rückgabe: Liste alle Bestellungen auf, die bis zum Enddatum vom Kunden nicht beglichen wurden; Finde die durchschnittliche Differenz zwischen dem Datum einer Bestellung und dem Datum deren Zahlung

**Comment by julianweise** [comment]
Alternativ Erweiterung der bestehenden Customer-Search-Queries mit einem Join auf offene Posten?

**Comment by Blaidd-Drwg** [comment]
Unsere Customer-Search kann so wie sie jetzt ist auch mehrere Ergebnisse zurückgeben, dann würden wir auch für Kunden, nach denen wir nicht gesucht haben, die Daten bekommen. Ich weiß ehrlich gesagt nicht, was bei Datenbanken best practice ist. Lieber eine große Anfrage mit Daten, die wir hinterher wegschmeißen, oder zwei kleinere?
