### ISSUE TITLE
Diagramm und Tabelle für 2b in Einklang bringen

### ISSUE THREAD

**Issue by frederike-ramin** [cmfcmf/sap-hana#40]
![unbenannt](https://cloud.githubusercontent.com/assets/9320199/15626525/d5d37dba-24c6-11e6-89cd-a7427e370067.png)
Das haut iwie noch nicht hin..

**Comment by julianweise** [comment]
Da ist in der Tat etwas komisch ...
![2016-05-28_1136](https://cloud.githubusercontent.com/assets/9257781/15626596/8c174e70-24c8-11e6-8291-08b9cbcd0782.png)
Aber die Daten liegen richtig in JavaScript vor.
![2016-05-28_1136_001](https://cloud.githubusercontent.com/assets/9257781/15626597/8de31e28-24c8-11e6-8850-7a00bd89114e.png)

@cmfcmf Hast du eine Idee, was da los ist?

**Comment by cmfcmf** [comment]
Ja :smile:

**Comment by cmfcmf** [comment]
Das sollte jetzt durch https://github.com/cmfcmf/sap-hana/pull/39/commits/448c51d15709a90336d58b16f7db9d56cafc4da4 behoben sein - allerdings habe ich es nicht getestet. Es lag daran, dass `(48,646)` nicht etwa eine Kommazahl in Klammern ist, sondern `48` und `646`, die mit dem Komma Operator verbunden sind, welcher ja bekanntlich den letzten Ausdruck, also `646` zurückgibt.

**Comment by julianweise** [comment]
Ohje ... :/
Danke dir :D
