### ISSUE TITLE
Datumsauswahl-Bug

### ISSUE THREAD

**Issue by frederike-ramin** [cmfcmf/sap-hana#41]
Wenn man das Datum nach der Vorschau (schonmal eingegebene Daten) auswählt und das Eingabefeld wechselt, wird statt des Datums, das bis eben noch drinstand, das aktuelle Datum (28.5.2016) reingeschrieben.

**Comment by cmfcmf** [comment]
Ich würde das mal als `wontfix` abstempeln?
